steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: create tarball from source
  entrypoint: /bin/tar
  args:
    - -czvf
    - /mnt/testing/blaise-mi-extract-csv.tar.gz
    - ./blaise-mi-extractcsv
  volumes:
    - name: "scratch"
      path: /mnt/testing
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  id: push zip to functions source bucket
  entrypoint: gsutil
  args:
    - -m
    - cp
    - /mnt/testing/blaise-mi-extract-csv.tar.gz
    - gs://ons-blaise-dev-blaise-cloud-functions-source/