steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "create zip from source"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        set -x && \
        apt-get update && \
        apt-get install -y zip && \
        ls && \
        zip /mnt/testing/blaise-mi-extract.zip ./*
    volumes:
      - name: "scratch"
        path: /mnt/testing

  - name: "gcr.io/cloud-builders/gcloud"
    id: "push zip to functions source bucket"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        gsutil cp /mnt/testing/blaise-mi-extract.zip gs://ons-blaise-dev-blaise-cloud-functions-source/
    volumes:
      - name: "scratch"
        path: /mnt/testing
